createOrReplace

	table 'f_MetaCarvao'
		lineageTag: 4641be81-282b-422c-9aa6-152e4328b756

		column 'Mês'
			dataType: dateTime
			formatString: dd/mm/yyyy
			lineageTag: 4632fd3e-b0b2-477c-9b1a-6ad43c428b56
			summarizeBy: none
			sourceColumn: Mês

		column 'UPC Partição'
			dataType: string
			lineageTag: 8c9af87b-9db3-4da3-b77a-4a5e7b3a3e15
			summarizeBy: none
			sourceColumn: UPC Partição

		column 'Código UPC'
			dataType: string
			lineageTag: c147532d-2692-4e19-9b0e-b8a08923b5b0
			summarizeBy: none
			sourceColumn: Código UPC

		column 'Tipo'
			dataType: string
			lineageTag: c5410979-4aa9-4149-9f6b-c0a800864a11
			summarizeBy: none
			sourceColumn: Tipo

		column 'DESTINO'
			dataType: string
			lineageTag: 5e32a191-d202-418b-aa23-03006f7490c6
			summarizeBy: none
			sourceColumn: DESTINO

		column 'Meta m³'
			dataType: double
			formatString: #,0
			lineageTag: 594f60eb-0f96-47a1-9c14-092f06804cb9
			summarizeBy: none
			sourceColumn: Meta m³

		partition 'f_MetaCarvao' = m
			mode: import
			source =
					// f_MetaCarvao — metas de carvão (m³) da planilha "Gestão da Partição".
					// Lê TODOS os arquivos "Gestão da Partição AAAA.xlsx" da pasta "Controle Partição" e TODAS as
					// abas de mês (Jan, Fev, ..., Setembro, Outubro, e as que forem criadas, como Novembro).
					// Uma aba entra quando tem o bloco "UPC - PRÓPRIA" com as colunas PLAN de CMG e RRP.
					// O mês vem da célula com a abreviação do mês no topo da aba (P4: "Out"); se faltar, do nome da aba.
					// O ano vem do nome do arquivo. A data da célula W1 NÃO é usada (na aba Agosto ela está 01/07).
					let
					    Meses    = [Jan = 1, Fev = 2, Mar = 3, Abr = 4, Mai = 5, Jun = 6, Jul = 7, Ago = 8,
					                Set = 9, Out = 10, Nov = 11, Dez = 12,
					                Janeiro = 1, Fevereiro = 2, Março = 3, Abril = 4, Maio = 5, Junho = 6, Julho = 7,
					                Agosto = 8, Setembro = 9, Outubro = 10, Novembro = 11, Dezembro = 12],
					    MesDe    = (v as any) as nullable number =>
					                   if v is text then Record.FieldOrDefault(Meses, Text.Proper(Text.Trim(v)), null) else null,

					    // lê uma aba no layout "PLANEJADO X REALIZADO - PUXADA DE CARVÃO"
					    LerAba   = (t as table, aba as text) as table =>
					        let
					            // células com erro (#REF!, #VALUE!, #NAME?) viram vazio: as abas de mês têm
					            // fórmulas quebradas da linha 108 para baixo e isso travava a carga
					            SemErro = Table.ReplaceErrorValues(t, List.Transform(Table.ColumnNames(t), each {_, null})),
					            Linhas = List.Buffer(Table.ToRows(SemErro)),
					            Pos    = (txt as text) as number =>
					                         List.PositionOf(List.Transform(Linhas, each List.Contains(_, txt)), true),
					            iProp  = Pos("UPC - PRÓPRIA"),
					            iCont  = Pos("UPC - CONTRATO"),
					            Cab    = if iProp >= 0 then Linhas{iProp} else {},
					            cNome  = List.PositionOf(Cab, "UPC - PRÓPRIA"),
					            cPlan  = List.PositionOf(Cab, "PLAN", Occurrence.All),
					            Topo   = List.Combine(List.FirstN(Linhas, 6)),
					            MesNum = List.First(List.RemoveNulls(List.Transform(Topo, MesDe)), MesDe(aba)),
					            Valida = iProp >= 0 and cNome >= 1 and List.Count(cPlan) >= 2 and MesNum <> null,
					            Idx    = if Valida then
					                         List.Select(List.Positions(Linhas), (i) =>
					                             i > iProp
					                             and Linhas{i}{cNome} is text
					                             and Text.StartsWith(Linhas{i}{cNome}, "UPC ")
					                             and Linhas{i}{cNome - 1} <> null)
					                     else {},
					            Saida  = List.Combine(List.Transform(Idx, (i) =>
					                         let
					                             r    = Linhas{i},
					                             tipo = if iCont >= 0 and i > iCont then "Contrato" else "Própria"
					                         in
					                             { {MesNum, r{cNome}, Text.From(r{cNome - 1}), tipo, "CMG", r{cPlan{0}}},
					                               {MesNum, r{cNome}, Text.From(r{cNome - 1}), tipo, "RRP", r{cPlan{1}}} })),
					            Tabela = #table({"MesNum", "UPC Partição", "Código UPC", "Tipo", "DESTINO", "Meta m³"}, Saida)
					        in
					            Table.SelectRows(Tabela, each [#"Meta m³"] is number and [#"Meta m³"] <> 0),

					    Pasta    = fnArquivosPasta(
					                   pSiteLog,
					                   {"Shared Documents", "Campo Grande", "4. Carvão", "Programação de Expedição",
					                    "Indicadores", "Controle Partição"}
					               ),
					    Arquivos = Table.SelectRows(Pasta, each Text.StartsWith(Text.Lower([Name]), "gest")
					                                          and Text.Contains(Text.Lower([Name]), "parti")),
					    ComAno   = Table.AddColumn(Arquivos, "Ano",
					                   each try Number.From(Text.Start(Text.Select([Name], {"0".."9"}), 4)) otherwise null,
					                   Int64.Type),
					    AnoOk    = Table.SelectRows(ComAno, each [Ano] <> null and [Ano] > 2000),
					    Abas     = Table.AddColumn(AnoOk, "Abas",
					                   each Table.SelectRows(Excel.Workbook([Content], false, true), each [Kind] = "Sheet"),
					                   type table),
					    Expande  = Table.ExpandTableColumn(Table.SelectColumns(Abas, {"Ano", "Abas"}), "Abas",
					                   {"Name", "Data"}, {"Aba", "Dados"}),
					    Lidas    = Table.AddColumn(Expande, "Metas", each LerAba([Dados], [Aba]), type table),
					    Empilha  = Table.ExpandTableColumn(Table.SelectColumns(Lidas, {"Ano", "Metas"}), "Metas",
					                   {"MesNum", "UPC Partição", "Código UPC", "Tipo", "DESTINO", "Meta m³"}),
					    // abas que não são de metas (SAP, Apoio, Info Partição...) voltam vazias e o expand
					    // mantém uma linha em branco para cada uma; sem este filtro o #date recebe mês null
					    SoMetas  = Table.SelectRows(Empilha, each [MesNum] is number and [#"Meta m³"] is number),
					    ComMes   = Table.AddColumn(SoMetas, "Mês", each #date([Ano], [MesNum], 1), type date),
					    Tipado   = Table.TransformColumnTypes(ComMes, {
					                   {"UPC Partição", type text}, {"Código UPC", type text}, {"Tipo", type text},
					                   {"DESTINO", type text}, {"Meta m³", type number}}),
					    Final    = Table.SelectColumns(Tipado, {"Mês", "UPC Partição", "Código UPC", "Tipo", "DESTINO", "Meta m³"})
					in
					    Final

	table 'd_UPC_Map'
		lineageTag: 584e455d-b0ba-497c-aad3-36ed080cbee3

		column 'UPC'
			dataType: string
			lineageTag: 1f55a7e0-ffbb-459f-9780-a03fed7ede84
			summarizeBy: none
			sourceColumn: UPC

		column 'UPC Partição'
			dataType: string
			lineageTag: b9d28000-766a-46c1-af0c-df55794874d4
			summarizeBy: none
			sourceColumn: UPC Partição

		partition 'd_UPC_Map' = m
			mode: import
			source =
					// d_UPC_Map — liga a UPC da base de puxada (f_basePlan) à UPC da planilha de partição.
					// A busca é por palavra-chave, na ordem da lista (OURO VERDE antes de LAJEADO, etc.).
					// UPC sem correspondência fica como "SEM META DE PARTIÇÃO": o carregado dela continua no total.
					// Para ligar uma UPC nova, acrescente {"PALAVRA DA BASE", "NOME NA PARTIÇÃO"} na lista.
					let
					    Mapa    = {
					                  {"OURO VERDE",      "UPC OURO VERDE"},
					                  {"MATA VERDE",      "UPC MATA VERDE"},
					                  {"VERDE MAR",       "UPC VERDE MAR"},
					                  {"LAJEADO",         "UPC LAGEADO"},
					                  {"LAGEADO",         "UPC LAGEADO"},
					                  {"NOVA DA MATA",    "UPC NOVA DA MATA"},
					                  {"CABECEIRA FUNDA", "UPC CABECEIRA FUNDA"},
					                  {"ÁGUA LIMPA",      "UPC ÁGUA LIMPA"},
					                  {"AGUA LIMPA",      "UPC ÁGUA LIMPA"},
					                  {"MÓVEL",           "UPC MÓVEL 1"},
					                  {"MOVEL",           "UPC MÓVEL 1"},
					                  {"BOM FUTURO",      "UPC BOM FUTURO"},
					                  {"LOBO",            "UPC LOBO"},
					                  {"SÃO JOÃO",        "UPC SÃO JOÃO"},
					                  {"MANGABA",         "UPC MANGABA"},
					                  {"AGROBUSINESS",    "UPC AGROBUSINESS"},
					                  {"DOURAFORTE",      "UPC DOURAFORTE"},
					                  {"FGMG",            "UPC FGMG"}
					              },
					    Fonte   = Table.Distinct(Table.SelectColumns(Table.SelectRows(f_basePlan, each [UPC] <> null), {"UPC"})),
					    ComPart = Table.AddColumn(Fonte, "UPC Partição", each
					                  let
					                      u   = Text.Upper([UPC]),
					                      hit = List.First(List.Select(Mapa, (p) => Text.Contains(u, p{0})), null)
					                  in
					                      if hit = null then "SEM META DE PARTIÇÃO" else hit{1},
					                  type text)
					in
					    ComPart

	table 'd_UPC_Carvao'
		lineageTag: 0a8ee5df-e382-4b44-bac7-055f69ce67f4

		column 'UPC Partição'
			dataType: string
			lineageTag: c44213cb-4c4d-4e91-8b3e-1d63d56aaaf0
			summarizeBy: none
			sourceColumn: UPC Partição

		column 'Tipo'
			dataType: string
			lineageTag: ce64d5ee-00df-49ba-9d5b-f58e6ae15a88
			summarizeBy: none
			sourceColumn: Tipo

		partition 'd_UPC_Carvao' = m
			mode: import
			source =
					// d_UPC_Carvao — uma linha por UPC da partição (com o Tipo mais recente: Própria/Contrato),
					// mais as UPCs da base que não estão na partição.
					let
					    DaMeta = Table.Buffer(Table.Sort(
					                 Table.SelectColumns(f_MetaCarvao, {"UPC Partição", "Tipo", "Mês"}),
					                 {{"Mês", Order.Descending}})),
					    Unicas = Table.Distinct(Table.SelectColumns(DaMeta, {"UPC Partição", "Tipo"}), {"UPC Partição"}),
					    DoMapa = Table.SelectRows(
					                 Table.Distinct(Table.SelectColumns(d_UPC_Map, {"UPC Partição"})),
					                 each not List.Contains(Unicas[UPC Partição], [UPC Partição])),
					    Extras = Table.AddColumn(DoMapa, "Tipo", each "Sem partição", type text),
					    Final  = Table.TransformColumnTypes(Table.Combine({Unicas, Extras}),
					                 {{"UPC Partição", type text}, {"Tipo", type text}})
					in
					    Final

	table 'Medidas Carvão'
		lineageTag: 66f4872e-b3b5-4934-b435-629381ecab76

		measure 'Meta Carvão (m³)' = ```
				-- meta mensal da partição para os meses do filtro de data (dia, mês ou ano)
				VAR _meses =
				    SELECTCOLUMNS (
				        SUMMARIZE ( d_Calendario, d_Calendario[Ano], d_Calendario[Mês Número] ),
				        "@Mes", DATE ( d_Calendario[Ano], d_Calendario[Mês Número], 1 )
				    )
				RETURN
				    CALCULATE ( SUM ( f_MetaCarvao[Meta m³] ), TREATAS ( _meses, f_MetaCarvao[Mês] ) )
				```
			formatString: #,0
			lineageTag: 02cba813-36be-4e1d-880b-63bc9c7e4588

		measure 'Carregado Carvão (m³)' = ```
				CALCULATE ( SUM ( f_basePlan[M³] ), KEEPFILTERS ( f_basePlan[CARREGADO] = "OK" ) )
				```
			formatString: #,0
			lineageTag: a346e962-cd8e-4c82-8921-e4311c4c75b7

		measure 'Dias com Carregamento' = ```
				CALCULATE ( DISTINCTCOUNT ( f_basePlan[DATA] ), KEEPFILTERS ( f_basePlan[CARREGADO] = "OK" ) )
				```
			formatString: 0
			lineageTag: 3097c727-822d-4ad4-8fc9-b8acde136936

		measure '% Atingimento Carvão' = ```
				DIVIDE ( [Carregado Carvão (m³)], [Meta Carvão (m³)], 0 )
				```
			formatString: 0.00%
			lineageTag: 4cfac09f-c59c-43a3-a189-8032bd60af8c

		measure 'Gap Carvão (m³)' = ```
				[Carregado Carvão (m³)] - [Meta Carvão (m³)]
				```
			formatString: #,0
			lineageTag: 239f52e5-92da-4057-8551-7110d50bd483

		measure 'Média Diária Carvão' = ```
				DIVIDE ( [Carregado Carvão (m³)], [Dias com Carregamento], 0 )
				```
			formatString: #,0
			lineageTag: 3a242a8e-810f-49e4-9cb9-c026558920ab

		measure 'Média Necessária Carvão' = ```
				-- quanto precisa carregar por dia, a partir de amanhã, para fechar a meta do mês (base D-1)
				VAR _base =
				    COALESCE (
				        CALCULATE ( MIN ( f_basePlan[DATA] ), KEEPFILTERS ( f_basePlan[CARREGADO] = "OK" ), ALLSELECTED ( f_basePlan[DATA] ), ALLSELECTED ( d_Calendario ) ),
				        MIN ( d_Calendario[Date] )
				    )
				VAR _fim  = EOMONTH ( _base, 0 )
				VAR _ref  = MIN ( TODAY () - 1, _fim )
				VAR _rest = DATEDIFF ( _ref, _fim, DAY )
				VAR _real = CALCULATE ( [Carregado Carvão (m³)], ALLSELECTED ( f_basePlan[DATA] ), ALLSELECTED ( d_Calendario ) )
				VAR _meta = CALCULATE ( [Meta Carvão (m³)], ALLSELECTED ( f_basePlan[DATA] ), ALLSELECTED ( d_Calendario ) )
				VAR _gap  = _meta - COALESCE ( _real, 0 )
				RETURN
				    SWITCH (
				        TRUE (),
				        ISBLANK ( _meta ), BLANK (),
				        _gap <= 0, 0,
				        _rest <= 0, BLANK (),
				        DIVIDE ( _gap, _rest )
				    )
				```
			formatString: #,0
			lineageTag: 30090a28-8862-4f34-bb48-3e5dab747cfd

		measure 'Lacuna Carvão' = ```
				-- dispersão: média realizada - média necessária. Vazia quando não há média necessária
				-- (mês já fechado ou sem meta); antes repetia a média realizada nesses casos
				VAR _nec = [Média Necessária Carvão]
				RETURN
				    IF ( NOT ISBLANK ( _nec ), [Média Diária Carvão] - _nec )
				```
			formatString: #,0
			lineageTag: 53de2a93-546a-4e53-b12c-20c1f3303c57

		measure 'Tendência Carvão (m³)' = ```
				-- projeção do mês: carregado + média diária x dias restantes (base D-1), limitada à meta.
				-- Calculada no nível do filtro atual: total na tela, por UPC/destino nas linhas da tabela.
				VAR _base =
				    COALESCE ( CALCULATE ( MIN ( f_basePlan[DATA] ), KEEPFILTERS ( f_basePlan[CARREGADO] = "OK" ) ), MIN ( d_Calendario[Date] ) )
				VAR _fim  = EOMONTH ( _base, 0 )
				VAR _ref  = MIN ( TODAY () - 1, _fim )
				VAR _real = [Carregado Carvão (m³)]
				VAR _dias = [Dias com Carregamento]
				VAR _meta = [Meta Carvão (m³)]
				VAR _rest = DATEDIFF ( _ref, _fim, DAY )
				VAR _proj = _real + DIVIDE ( _real, _dias ) * _rest
				RETURN
				    SWITCH (
				        TRUE (),
				        ISBLANK ( _meta ) || _meta <= 0, BLANK (),
				        ISBLANK ( _real ), 0,
				        _real >= _meta, _meta,
				        _rest <= 0, _real,
				        MIN ( _proj, _meta )
				    )
				```
			formatString: #,0
			lineageTag: b0c399a4-b9a6-4b7e-8826-1bb95a0af63f

		measure '% Ritmo Carvão' = ```
				DIVIDE ( [Tendência Carvão (m³)], [Meta Carvão (m³)], 0 )
				```
			formatString: 0.00%
			lineageTag: a04de388-2ebd-4a30-8eda-8edbf7db9468

		measure 'Previsão Carvão' = ```
				-- último dia carregado + dias que faltam no ritmo atual para fechar a meta
				VAR _med  = CALCULATE ( [Média Diária Carvão], ALLSELECTED ( f_basePlan[DATA] ), ALLSELECTED ( d_Calendario ) )
				VAR _gap  = CALCULATE ( [Gap Carvão (m³)], ALLSELECTED ( f_basePlan[DATA] ), ALLSELECTED ( d_Calendario ) )
				VAR _falta = IF ( _gap < 0, -_gap, 0 )
				VAR _last = CALCULATE ( MAX ( f_basePlan[DATA] ), KEEPFILTERS ( f_basePlan[CARREGADO] = "OK" ), ALLSELECTED ( f_basePlan[DATA] ), ALLSELECTED ( d_Calendario ) )
				RETURN
				    SWITCH (
				        TRUE (),
				        ISBLANK ( _last ), BLANK (),
				        _falta = 0, _last,
				        _med = 0, BLANK (),
				        _last + ROUNDUP ( DIVIDE ( _falta, _med ), 0 )
				    )
				```
			formatString: dd/mm/yyyy
			lineageTag: 01d509cf-86ff-406b-bb9e-787e13bf5c4e

		measure 'Dias de Chegada Carvão' = ```
				VAR _prev = [Previsão Carvão]
				RETURN
				    IF ( ISBLANK ( _prev ), BLANK (), MAX ( DATEDIFF ( TODAY (), _prev, DAY ), 0 ) )
				```
			formatString: 0
			lineageTag: 8f4ce4d2-629f-40e5-9eb3-1168441399a2

		measure 'Contagem de Dias Carvão' = ```
				VAR _base =
				    COALESCE (
				        CALCULATE ( MIN ( f_basePlan[DATA] ), KEEPFILTERS ( f_basePlan[CARREGADO] = "OK" ), ALLSELECTED ( f_basePlan[DATA] ), ALLSELECTED ( d_Calendario ) ),
				        CALCULATE ( MIN ( d_Calendario[Date] ), ALLSELECTED ( d_Calendario ) )
				    )
				VAR _ini = DATE ( YEAR ( _base ), MONTH ( _base ), 1 )
				VAR _fim = EOMONTH ( _base, 0 )
				-- Base é D-1: referência é o último dia fechado (ontem)
				VAR _ref = MIN ( TODAY () - 1, _fim )
				VAR DiasTotais     = DAY ( _fim )
				VAR DiasDecorridos = MAX ( DATEDIFF ( _ini, _ref, DAY ) + 1, 0 )
				VAR DiasRestantes  = DiasTotais - DiasDecorridos
				RETURN
				    IF (
				        ISBLANK ( _base ),
				        "Sem carregamento no período",
				        "Dias totais: " & DiasTotais & UNICHAR ( 10 ) &
				        "Dias decorridos: " & DiasDecorridos & UNICHAR ( 10 ) &
				        "Faltam: " & DiasRestantes & " dias"
				    )
				```
			lineageTag: 425557e5-632a-4eb1-9519-1da3fabf7152

		measure 'Média Realizada Carvão (Mês)' = ```
				-- linha "média realizada" dos gráficos: média diária do mês do ponto, até ontem
				VAR _d0  = MIN ( d_Calendario[Date] )
				VAR _d   = MAX ( d_Calendario[Date] )
				VAR _ini = DATE ( YEAR ( _d ), MONTH ( _d ), 1 )
				VAR _ref = MIN ( TODAY () - 1, EOMONTH ( _d, 0 ) )
				VAR _v =
				    CALCULATE (
				        [Média Diária Carvão],
				        REMOVEFILTERS ( d_Calendario ),
				        DATESBETWEEN ( d_Calendario[Date], _ini, _ref )
				    )
				RETURN
				    IF ( _d0 <= _ref, _v )
				```
			formatString: #,0
			lineageTag: 69df44ba-ccb5-4363-af68-49b49c54f536

		measure 'Média Necessária Carvão (Mês)' = ```
				-- linha "média necessária" dos gráficos: o que falta da meta do mês / dias que faltam
				VAR _d    = MIN ( d_Calendario[Date] )
				VAR _ini  = DATE ( YEAR ( _d ), MONTH ( _d ), 1 )
				VAR _fim  = EOMONTH ( _d, 0 )
				VAR _ref  = MIN ( TODAY () - 1, _fim )
				VAR _real =
				    CALCULATE (
				        [Carregado Carvão (m³)],
				        REMOVEFILTERS ( d_Calendario ),
				        DATESBETWEEN ( d_Calendario[Date], _ini, _ref )
				    )
				VAR _meta =
				    CALCULATE (
				        [Meta Carvão (m³)],
				        REMOVEFILTERS ( d_Calendario ),
				        DATESBETWEEN ( d_Calendario[Date], _ini, _fim )
				    )
				VAR _rest = DATEDIFF ( _ref, _fim, DAY )
				VAR _gap  = _meta - COALESCE ( _real, 0 )
				RETURN
				    SWITCH (
				        TRUE (),
				        ISBLANK ( _meta ), BLANK (),
				        _gap <= 0, 0,
				        _rest <= 0, BLANK (),
				        DIVIDE ( _gap, _rest )
				    )
				```
			formatString: #,0
			lineageTag: 5da17e8d-0f22-48c9-b3a3-0b161125a78b

		measure 'Estoque Carvão CMG' = ```
				VAR _u =
				    CALCULATE (
				        MAX ( f_Estoque_VS[DATA] ),
				        KEEPFILTERS (
				            FILTER (
				                f_Estoque_VS,
				                NOT ISBLANK ( f_Estoque_VS[ESTOQUE - VS CMG] ) || f_Estoque_VS[ESTOQUE - VS RRP - TOTAL] <> 0
				            )
				        )
				    )
				RETURN
				    CALCULATE ( SUM ( f_Estoque_VS[ESTOQUE - VS CMG] ), REMOVEFILTERS ( d_Calendario ), f_Estoque_VS[DATA] = _u )
				```
			formatString: #,0
			lineageTag: 095beed9-bae8-4acd-9341-433cf813c3f0

		measure 'Estoque Carvão RRP' = ```
				VAR _u =
				    CALCULATE (
				        MAX ( f_Estoque_VS[DATA] ),
				        KEEPFILTERS (
				            FILTER (
				                f_Estoque_VS,
				                NOT ISBLANK ( f_Estoque_VS[ESTOQUE - VS CMG] ) || f_Estoque_VS[ESTOQUE - VS RRP - TOTAL] <> 0
				            )
				        )
				    )
				RETURN
				    CALCULATE ( SUM ( f_Estoque_VS[ESTOQUE - VS RRP - TOTAL] ), REMOVEFILTERS ( d_Calendario ), f_Estoque_VS[DATA] = _u )
				```
			formatString: #,0
			lineageTag: 5dff37eb-5bfa-4f5e-8c10-b8d5ce6c06de

		measure 'Estoque Carvão Total' = ```
				[Estoque Carvão CMG] + [Estoque Carvão RRP]
				```
			formatString: #,0
			lineageTag: 919f43da-700f-476b-8499-2d162f4a2c99

		measure 'Estoque Carvão Animado' = ```
				-- mesmo formato do "Estoque Gusa Animado": um bloco por filial (RRP e CMG) com o
				-- estoque da última posição do período e as barras dos últimos 7 dias
				VAR _u =
				    CALCULATE (
				        MAX ( f_Estoque_VS[DATA] ),
				        KEEPFILTERS (
				            FILTER (
				                f_Estoque_VS,
				                NOT ISBLANK ( f_Estoque_VS[ESTOQUE - VS CMG] ) || f_Estoque_VS[ESTOQUE - VS RRP - TOTAL] <> 0
				            )
				        )
				    )
				VAR _dias =
				    CALCULATETABLE (
				        TOPN (
				            7,
				            FILTER (
				                VALUES ( f_Estoque_VS[DATA] ),
				                NOT ISBLANK ( CALCULATE ( MAX ( f_Estoque_VS[ESTOQUE - VS CMG] ) ) )
				                    || CALCULATE ( MAX ( f_Estoque_VS[ESTOQUE - VS RRP - TOTAL] ) ) <> 0
				            ),
				            f_Estoque_VS[DATA], DESC
				        ),
				        REMOVEFILTERS ( d_Calendario ),
				        f_Estoque_VS[DATA] <= _u
				    )
				VAR _filiais =
				    DATATABLE ( "Sigla", STRING, "Ordem", INTEGER, { { "RRP", 0 }, { "CMG", 1 } } )
				VAR _hb = 90    -- altura máxima da barra
				VAR _blocos =
				    CONCATENATEX (
				        _filiais,
				        VAR _s    = [Sigla]
				        VAR _i    = [Ordem]
				        VAR _y    = 8 + _i * 203
				        VAR _solo = _y + 150
				        VAR _atr  = _i * 300
				        VAR _vals =
				            ADDCOLUMNS (
				                _dias,
				                "@V",
				                    VAR _d = f_Estoque_VS[DATA]
				                    RETURN
				                        CALCULATE (
				                            IF (
				                                _s = "CMG",
				                                SUM ( f_Estoque_VS[ESTOQUE - VS CMG] ),
				                                SUM ( f_Estoque_VS[ESTOQUE - VS RRP - TOTAL] )
				                            ),
				                            REMOVEFILTERS ( d_Calendario ),
				                            f_Estoque_VS[DATA] = _d
				                        )
				            )
				        VAR _atual = MAXX ( FILTER ( _vals, f_Estoque_VS[DATA] = _u ), [@V] )
				        VAR _mx    = MAX ( MAXX ( _vals, [@V] ), 1 )
				        VAR _barras =
				            CONCATENATEX (
				                _vals,
				                VAR _d   = f_Estoque_VS[DATA]
				                VAR _v   = [@V]
				                VAR _k   = COUNTROWS ( FILTER ( _vals, f_Estoque_VS[DATA] < _d ) ) + 0
				                VAR _x   = 30 + _k * 48
				                VAR _h   = IF ( _v > 0, MAX ( 3, INT ( DIVIDE ( _v, _mx ) * _hb ) ), 0 )
				                VAR _cor = IF ( _d = _u, "#284D38", "#4D8264" )
				                RETURN
				                    IF ( _h = 0, "",
				                        "<g transform=""translate(" & _x & "," & _solo & ")""><g>" &
				                        "<animateTransform attributeName=""transform"" type=""scale"" values=""1 0;1 1"" dur=""500ms"" begin=""" & ( _atr + _k * 80 ) & "ms"" fill=""freeze""/>" &
				                        "<rect x=""0"" y=""-" & _h & """ width=""32"" height=""" & _h & """ fill=""" & _cor & """/></g></g>" ) &
				                    "<text x=""" & ( _x + 16 ) & """ y=""" & ( _solo - _h - 6 ) & """ font-size=""11"" text-anchor=""middle"" fill=""#3D3D3A"" opacity=""0"">" & FORMAT ( _v, "#,##0" ) &
				                        "<animate attributeName=""opacity"" values=""0;1"" dur=""300ms"" begin=""" & ( _atr + 500 + _k * 80 ) & "ms"" fill=""freeze""/></text>" &
				                    "<text x=""" & ( _x + 16 ) & """ y=""" & ( _solo + 16 ) & """ font-size=""11"" text-anchor=""middle"" fill=""#5F5E5A"">" & FORMAT ( _d, "dd/mm" ) & "</text>",
				                "",
				                f_Estoque_VS[DATA], ASC
				            )
				        RETURN
				            -- moldura do bloco
				            "<rect x=""4"" y=""" & _y & """ width=""570"" height=""191"" rx=""10"" fill=""#FFFFFF"" stroke=""#E5E3DC"" stroke-width=""1""/>" &
				            "<text x=""24"" y=""" & ( _y + 26 ) & """ font-size=""12"" font-weight=""600"" fill=""#284D38"">ESTOQUE DE CARVÃO (m³):</text>" &
				            "<text x=""24"" y=""" & ( _y + 44 ) & """ font-size=""11"" fill=""#5F5E5A"">posição de " & FORMAT ( _u, "dd/mm/yyyy" ) & " e últimos 7 dias</text>" &
				            "<text x=""465"" y=""" & ( _y + 42 ) & """ font-size=""30"" font-weight=""600"" text-anchor=""middle"" fill=""#284D38"">" & _s & "</text>" &
				            -- cartão do total
				            "<rect x=""380"" y=""" & ( _y + 54 ) & """ width=""170"" height=""110"" rx=""8"" fill=""#1E4430"" opacity=""0"">" &
				                "<animate attributeName=""opacity"" values=""0;1"" dur=""400ms"" begin=""" & ( _atr + 600 ) & "ms"" fill=""freeze""/></rect>" &
				            "<rect x=""380"" y=""" & ( _y + 54 ) & """ width=""170"" height=""110"" rx=""8"" fill=""#FFFFFF"" opacity=""0"">" &
				                "<animate attributeName=""opacity"" values=""0;0.12;0"" dur=""2800ms"" begin=""" & ( _atr + 1200 ) & "ms"" repeatCount=""indefinite""/></rect>" &
				            "<text x=""465"" y=""" & ( _y + 88 ) & """ font-size=""15"" text-anchor=""middle"" fill=""#FFFFFF"" opacity=""0"">Estoque Atual" &
				                "<animate attributeName=""opacity"" values=""0;1"" dur=""400ms"" begin=""" & ( _atr + 700 ) & "ms"" fill=""freeze""/></text>" &
				            "<text x=""465"" y=""" & ( _y + 134 ) & """ font-size=""32"" font-weight=""600"" text-anchor=""middle"" fill=""#FFFFFF"" opacity=""0"">" & FORMAT ( _atual, "#,##0" ) &
				                "<animate attributeName=""opacity"" values=""0;1"" dur=""400ms"" begin=""" & ( _atr + 800 ) & "ms"" fill=""freeze""/></text>" &
				            _barras,
				        "",
				        [Ordem], ASC
				    )
				RETURN
				    IF (
				        ISBLANK ( _u ),
				        "<div style=""font:13px sans-serif;color:#5F5E5A"">Sem estoque no filtro atual</div>",
				        "<div style=""width:100%;overflow:hidden"">" &
				        "<svg xmlns=""http://www.w3.org/2000/svg"" width=""100%"" viewBox=""0 0 578 411"" preserveAspectRatio=""xMidYMid meet"">" &
				            _blocos &
				        "</svg></div>"
				    )
				```
			lineageTag: ebef16e5-25d1-4f90-9e46-f27cc00e5cce

		measure 'Viagens Planejadas Carvão' = ```
				-- cargas programadas na puxada (OK + NOK + ainda sem status)
				COUNTROWS ( f_basePlan )
				```
			formatString: #,0
			lineageTag: a2feaebd-c049-4941-8304-950422039b40

		measure 'Viagens Realizadas Carvão' = ```
				CALCULATE ( COUNTROWS ( f_basePlan ), KEEPFILTERS ( f_basePlan[CARREGADO] = "OK" ) )
				```
			formatString: #,0
			lineageTag: e3b60c0e-051c-4c0c-b2ec-8cda56032839

		measure 'Viagens Canceladas Carvão' = ```
				-- carga programada e cancelada (CARREGADO = "NOK")
				CALCULATE ( COUNTROWS ( f_basePlan ), KEEPFILTERS ( f_basePlan[CARREGADO] = "NOK" ) )
				```
			formatString: #,0
			lineageTag: 2b92b907-4270-4064-921a-72ed17b7b99a

		measure 'Canceladas Carvão (m³)' = ```
				CALCULATE ( SUM ( f_basePlan[M³] ), KEEPFILTERS ( f_basePlan[CARREGADO] = "NOK" ) )
				```
			formatString: #,0
			lineageTag: a4edd129-8989-4509-87ee-4ff05122ba7d

		measure '% Canceladas Carvão' = ```
				DIVIDE ( [Viagens Canceladas Carvão], [Viagens Planejadas Carvão] )
				```
			formatString: 0.00%
			lineageTag: 44e7d853-e75e-432a-b0fe-865d87f08f38

		measure 'Furos Carvão' = ```
				-- carga programada para um dia que já passou (até ontem) e que ficou sem status:
				-- não carregou (OK) nem foi cancelada (NOK)
				CALCULATE (
				    COUNTROWS ( f_basePlan ),
				    KEEPFILTERS ( ISBLANK ( f_basePlan[CARREGADO] ) || NOT ( f_basePlan[CARREGADO] IN { "OK", "NOK" } ) ),
				    KEEPFILTERS ( f_basePlan[DATA] < TODAY () )
				)
				```
			formatString: #,0
			lineageTag: 129bea58-5dff-44ac-a62e-9526e85d087b

		measure 'Viagens a Realizar Carvão' = ```
				-- programadas para hoje em diante, ainda sem status
				[Viagens Planejadas Carvão]
				    - COALESCE ( [Viagens Realizadas Carvão], 0 )
				    - COALESCE ( [Viagens Canceladas Carvão], 0 )
				    - COALESCE ( [Furos Carvão], 0 )
				```
			formatString: #,0
			lineageTag: 945a2d36-9407-4b08-98cc-1dec1627b4c6

		measure '% Furo Carvão' = ```
				DIVIDE ( [Furos Carvão], [Viagens Planejadas Carvão] )
				```
			formatString: 0.00%
			lineageTag: beff9ae0-c600-4b4c-9310-f99866d28e6b

		column Coluna
			dataType: string
			isHidden
			lineageTag: 82a8aefd-d348-45c0-8c0c-05d84353b183
			summarizeBy: none
			sourceColumn: Coluna

		partition 'Medidas Carvão' = m
			mode: import
			source =
					#table(type table [Coluna = text], {})

	relationship 90a2fd38-3814-495c-8db4-b8eaf646b8e8
		fromColumn: f_MetaCarvao.'UPC Partição'
		toColumn: d_UPC_Carvao.'UPC Partição'

	relationship 5501f7ce-a9b8-41eb-bd6d-af54eb61015c
		fromColumn: d_UPC_Map.'UPC Partição'
		toColumn: d_UPC_Carvao.'UPC Partição'

	relationship 7a0d641f-c45f-4634-a9e7-5326dfccb3c6
		fromColumn: f_basePlan.UPC
		toColumn: d_UPC_Map.UPC

	relationship e9215339-9ee6-4919-a6cb-3c452d50e6a6
		fromColumn: f_MetaCarvao.DESTINO
		toColumn: d_Destino.DESTINO
